version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
     -  "3000:3000"
    networks:
      - app-network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenthub
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mariadb

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/studenthub.bhsi.xyz/html
      - ./nginx-conf:/etc/nginx/conf.d/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/studenthub.bhsi.xyz/
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/studenthub.bhsi.xyz/html
      - ./certbot/www/:/var/www/studenthub.bhsi.xyz/
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/studenthub.bhsi.xyz/html --email miadong179@gmail.com --agree-tos --no-eff-email --staging -d www.studenthub.bhsi.xyz  -d www.studenthub.bhsi.xyz

volumes:
  db-data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/s205353/node_project/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/s205353/node_project/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
